-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jun 30, 2020 at 07:02 AM
-- Server version: 5.7.24
-- PHP Version: 7.2.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `fano211`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `id_adm` int(2) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL,
  `nama_adm` varchar(100) NOT NULL,
  `foto_adm` varchar(255) DEFAULT NULL,
  `moto_adm` varchar(255) NOT NULL,
  `whatsapp` varchar(15) DEFAULT NULL,
  `instagram` varchar(255) DEFAULT NULL,
  `facebook` varchar(255) DEFAULT NULL,
  `twitter` varchar(255) DEFAULT NULL,
  `youtube` varchar(255) DEFAULT NULL,
  `active` int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`id_adm`, `username`, `password`, `nama_adm`, `foto_adm`, `moto_adm`, `whatsapp`, `instagram`, `facebook`, `twitter`, `youtube`, `active`) VALUES
(1, 'ahauwlie@gmail.com', '$2y$10$RrG2UJkz20AgXuJ7yPYjpelg4Yov43XYACM6PT3XUIHI4MbzPAm3a', 'ahauwlie', 'http://localhost/fano2.11_CI_KOYOS/inti/images/upload/11.JPG', 'mau nyoba dulu nihh', '', '', '', '', '', 1);

-- --------------------------------------------------------

--
-- Table structure for table `barang`
--

CREATE TABLE `barang` (
  `id_bar` int(2) NOT NULL,
  `nama_bar` varchar(100) NOT NULL,
  `deskripsi_bar` text NOT NULL,
  `harga_bar` int(9) NOT NULL,
  `sku_bar` int(12) NOT NULL,
  `ukuran_xs_bar` varchar(2) DEFAULT NULL,
  `ukuran_s_bar` varchar(2) DEFAULT NULL,
  `ukuran_m_bar` varchar(2) NOT NULL,
  `ukuran_l_bar` varchar(2) DEFAULT NULL,
  `ukuran_xl_bar` varchar(2) DEFAULT NULL,
  `ukuran_xxl_bar` varchar(2) DEFAULT NULL,
  `bebas_1_bar` varchar(255) NOT NULL,
  `bebas_2_bar` varchar(255) NOT NULL,
  `stock_bar` int(3) NOT NULL,
  `kategori_bar` varchar(50) NOT NULL,
  `img_1_bar` varchar(255) NOT NULL,
  `img_2_bar` varchar(255) DEFAULT NULL,
  `img_3_bar` varchar(255) DEFAULT NULL,
  `img_4_bar` varchar(255) DEFAULT NULL,
  `img_5_bar` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `barang`
--

INSERT INTO `barang` (`id_bar`, `nama_bar`, `deskripsi_bar`, `harga_bar`, `sku_bar`, `ukuran_xs_bar`, `ukuran_s_bar`, `ukuran_m_bar`, `ukuran_l_bar`, `ukuran_xl_bar`, `ukuran_xxl_bar`, `bebas_1_bar`, `bebas_2_bar`, `stock_bar`, `kategori_bar`, `img_1_bar`, `img_2_bar`, `img_3_bar`, `img_4_bar`, `img_5_bar`) VALUES
(146, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250000, 2020063001, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 27, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(147, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250001, 2020063002, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 28, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(148, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250002, 2020063003, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 29, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(149, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250003, 2020063004, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 30, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(150, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250004, 2020063005, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 31, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(151, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250005, 2020063006, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 32, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(152, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250006, 2020063007, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 33, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(153, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250007, 2020063008, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 34, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(154, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250008, 2020063009, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 35, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(155, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250009, 2020063010, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 36, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(156, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250010, 2020063011, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 37, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(157, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250011, 2020063012, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 38, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(158, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250012, 2020063013, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 39, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(159, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250013, 2020063014, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 40, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(160, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250014, 2020063015, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 41, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(161, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250015, 2020063016, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 42, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(162, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250016, 2020063017, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 43, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(163, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250017, 2020063018, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 44, 'nyoba_aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(164, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250018, 2020063019, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 45, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(165, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250019, 2020063020, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 46, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(166, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250020, 2020063021, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 47, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(167, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250021, 2020063022, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 48, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(168, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250022, 2020063023, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 49, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(169, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250023, 2020063024, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 50, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(170, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250024, 2020063025, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 51, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(171, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250025, 2020063026, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 52, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(172, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250026, 2020063027, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 53, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(173, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250027, 2020063028, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 54, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(174, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250028, 2020063029, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 55, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(175, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250029, 2020063030, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 56, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(176, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250030, 2020063031, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 57, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(177, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250031, 2020063032, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 58, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(178, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250032, 2020063033, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 59, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(179, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250033, 2020063034, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 60, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(180, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250034, 2020063035, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 61, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(181, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250035, 2020063036, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 62, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(182, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250036, 2020063037, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 63, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(183, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250037, 2020063038, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 64, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(184, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250038, 2020063039, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 65, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(185, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250039, 2020063040, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 66, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(186, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250040, 2020063041, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 67, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(187, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250041, 2020063042, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 68, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(188, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250042, 2020063043, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 69, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(189, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250043, 2020063044, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 70, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png');
INSERT INTO `barang` (`id_bar`, `nama_bar`, `deskripsi_bar`, `harga_bar`, `sku_bar`, `ukuran_xs_bar`, `ukuran_s_bar`, `ukuran_m_bar`, `ukuran_l_bar`, `ukuran_xl_bar`, `ukuran_xxl_bar`, `bebas_1_bar`, `bebas_2_bar`, `stock_bar`, `kategori_bar`, `img_1_bar`, `img_2_bar`, `img_3_bar`, `img_4_bar`, `img_5_bar`) VALUES
(190, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250044, 2020063045, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 71, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(191, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250045, 2020063046, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 72, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(192, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250046, 2020063047, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 73, 'nyoba_doang', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(193, 'Nama Barang', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 250047, 2020063048, 'xs', 's', 'm', 'l', 'xl', 'xx', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', 74, 'nyoba_1', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png');

-- --------------------------------------------------------

--
-- Table structure for table `blog`
--

CREATE TABLE `blog` (
  `id_blog` int(2) NOT NULL,
  `judul_blog` varchar(150) NOT NULL,
  `deskripsi_blog` text NOT NULL,
  `mini_text_blog` varchar(113) NOT NULL,
  `tanggal_blog` date NOT NULL,
  `nama_admin_blog` varchar(100) NOT NULL,
  `kategori_blog` varchar(50) NOT NULL,
  `img_1_blog` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `blog`
--

INSERT INTO `blog` (`id_blog`, `judul_blog`, `deskripsi_blog`, `mini_text_blog`, `tanggal_blog`, `nama_admin_blog`, `kategori_blog`, `img_1_blog`) VALUES
(75, 'What is Lorem Ipsum? 1', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(76, 'What is Lorem Ipsum? 2', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(77, 'What is Lorem Ipsum? 3', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2007-01-20', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(78, 'What is Lorem Ipsum? 4', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2007-02-20', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(79, 'What is Lorem Ipsum? 5', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2007-03-20', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(80, 'What is Lorem Ipsum? 6', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2007-04-20', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(81, 'What is Lorem Ipsum? 7', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2007-05-20', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(82, 'What is Lorem Ipsum? 8', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2007-06-20', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(83, 'What is Lorem Ipsum? 9', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2007-07-20', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(84, 'What is Lorem Ipsum? 10', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2007-08-20', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(85, 'What is Lorem Ipsum? 11', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2007-09-20', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(86, 'What is Lorem Ipsum? 12', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2007-10-20', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(87, 'What is Lorem Ipsum? 13', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2007-11-20', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(88, 'What is Lorem Ipsum? 14', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2007-12-20', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(89, 'What is Lorem Ipsum? 15', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(90, 'What is Lorem Ipsum? 16', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(91, 'What is Lorem Ipsum? 17', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(92, 'What is Lorem Ipsum? 18', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Nyoba aja', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(93, 'What is Lorem Ipsum? 19', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Hayooo', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(94, 'What is Lorem Ipsum? 20', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Hayooo', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(95, 'What is Lorem Ipsum? 21', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Hayooo', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(96, 'What is Lorem Ipsum? 22', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Hayooo', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(97, 'What is Lorem Ipsum? 23', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Hayooo', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(98, 'What is Lorem Ipsum? 24', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Hayooo', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(99, 'What is Lorem Ipsum? 25', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Hayooo', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(100, 'What is Lorem Ipsum? 26', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Hayooo', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(101, 'What is Lorem Ipsum? 27', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Hayooo', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(102, 'What is Lorem Ipsum? 28', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Hayooo', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(103, 'What is Lorem Ipsum? 29', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Hayooo', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(104, 'What is Lorem Ipsum? 30', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'Hayooo', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(105, 'What is Lorem Ipsum? 31', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'eeeaaaa', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(106, 'What is Lorem Ipsum? 32', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'eeeaaaa', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(107, 'What is Lorem Ipsum? 33', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '0000-00-00', 'ahauwlie', 'eeeaaaa', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(108, 'What is Lorem Ipsum? 34', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2008-01-20', 'ahauwlie', 'eeeaaaa', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(109, 'What is Lorem Ipsum? 35', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2008-02-20', 'ahauwlie', 'eeeaaaa', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png'),
(110, 'What is Lorem Ipsum? 36', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.', '2008-03-20', 'ahauwlie', 'eeeaaaa', 'http://localhost/fano2.11_CI_KOYOS/inti/images/photo.png');

-- --------------------------------------------------------

--
-- Table structure for table `comment`
--

CREATE TABLE `comment` (
  `id_com` int(11) NOT NULL,
  `id_blog` int(8) NOT NULL,
  `parent_id` int(11) NOT NULL,
  `comment_name` varchar(100) NOT NULL,
  `comment_email` varchar(100) NOT NULL,
  `comment_body` text NOT NULL,
  `comment_state` tinyint(1) NOT NULL,
  `comment_created` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id_adm`);

--
-- Indexes for table `barang`
--
ALTER TABLE `barang`
  ADD PRIMARY KEY (`id_bar`);

--
-- Indexes for table `blog`
--
ALTER TABLE `blog`
  ADD PRIMARY KEY (`id_blog`);

--
-- Indexes for table `comment`
--
ALTER TABLE `comment`
  ADD PRIMARY KEY (`id_com`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `id_adm` int(2) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `barang`
--
ALTER TABLE `barang`
  MODIFY `id_bar` int(2) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=194;

--
-- AUTO_INCREMENT for table `blog`
--
ALTER TABLE `blog`
  MODIFY `id_blog` int(2) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=111;

--
-- AUTO_INCREMENT for table `comment`
--
ALTER TABLE `comment`
  MODIFY `id_com` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
